steps:
  # 1. Constrói a imagem Docker
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--no-cache'
    - '-t'
    - 'southamerica-east1-docker.pkg.dev/teste-notificacao-barbearia/barbearia-repo/barbearia-app:latest'
    - '.'

  # 2. Envia a imagem para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'southamerica-east1-docker.pkg.dev/teste-notificacao-barbearia/barbearia-repo/barbearia-app:latest'

  # 3. Faz o deploy da nova imagem no Google Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'barbearia-backend-service'
    - '--image'
    - 'southamerica-east1-docker.pkg.dev/teste-notificacao-barbearia/barbearia-repo/barbearia-app:latest'
    - '--platform'
    - 'managed'
    - '--region'
    - 'southamerica-east1'
    - '--allow-unauthenticated'
    # ========== SECRETS (Firebase + APNs) ==========
    # Firebase: montado como variável de ambiente
    # APNs: montado como arquivo em /app/secrets/apns-auth-key.p8
    - '--set-secrets'
    - 'FIREBASE_ADMIN_CREDENTIALS=firebase-admin-credentials:latest,/app/secrets/apns-auth-key.p8=apns-auth-key:latest'
    # ========== VARIÁVEIS DE AMBIENTE ==========
    # Variáveis existentes + novas variáveis APNs
    - '--set-env-vars'
    - 'CLOUD_STORAGE_BUCKET_NAME=barbearia-app-fotoss,GCP_PROJECT_ID=teste-notificacao-barbearia,KMS_CRYPTO_KEY_NAME=projects/teste-notificacao-barbearia/locations/southamerica-east1/keyRings/barbearia-app-keys/cryptoKeys/firestore-data-key/cryptoKeyVersions/1,APNS_KEY_PATH=/app/secrets/apns-auth-key.p8,APNS_KEY_ID=UD85TPJ89Y,APNS_TEAM_ID=M83XX73UUS,APNS_TOPIC=web.ygg.conciergeanalicegrubert,APNS_USE_SANDBOX=False'

# Define a imagem que foi construída
images:
  - 'southamerica-east1-docker.pkg.dev/teste-notificacao-barbearia/barbearia-repo/barbearia-app:latest'

# Adiciona a configuração de logging
options:
  logging: CLOUD_LOGGING_ONLY
